# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
import cv2 
import sys
import json

from passport_data import *

class DisplayImageWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(DisplayImageWidget, self).__init__(parent)

        self.image_frame = QtWidgets.QLabel()
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.addWidget(self.image_frame)
        self.setLayout(self.layout)
        
        self.image = cv2.imread('123.png')
        self.image = QtGui.QImage(self.image.data, self.image.shape[1], self.image.shape[0], QtGui.QImage.Format_RGB888)
        self.image_frame.setPixmap(QtGui.QPixmap.fromImage(self.image))      
        


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 560)

        #self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        #self.verticalLayout.setObjectName("verticalLayout")

        ##Label as image code
        #self.infoLabel = QtWidgets.QLabel()
        #pixmap = QtGui.QPixmap("123.png")
        #self.infoLabel.setPixmap(pixmap)
        #self.infoLabel.resize(100, 100)
        #print(QtGui.QImageReader.supportedImageFormats()) 
        #self.verticalLayout.addWidget(self.infoLabel)
        #
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.serEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.serEdit.setGeometry(QtCore.QRect(780, 30, 90, 20))

        #серия паспорта
        self.serEdit.setObjectName("serEdit")
        self.serLabel = QtWidgets.QLabel(self.centralwidget)
        self.serLabel.setGeometry(QtCore.QRect(780, 10, 55, 20))
        self.serLabel.setObjectName("serLabel")

        #номер паспорта
        self.numEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.numEdit.setGeometry(QtCore.QRect(910, 30, 115, 20))
        self.numEdit.setObjectName("numEdit")

        self.numLabel = QtWidgets.QLabel(self.centralwidget)
        self.numLabel.setGeometry(QtCore.QRect(910, 10, 55, 20))
        self.numLabel.setObjectName("numLabel")

        #кнопка Ок
        self.ok = QtWidgets.QPushButton(self.centralwidget)
        self.ok.setGeometry(QtCore.QRect(802, 480, 130, 30))
        self.ok.setObjectName("ok")
        self.ok.clicked.connect(self.buttonOkClicked)
        
        #кнопка выхода
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(960, 480, 90, 30))
        self.exit.setObjectName("exit")
        self.exit.clicked.connect(sys.exit)


        #
        self.dateEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.dateEdit_1.setGeometry(QtCore.QRect(730, 90, 320, 20))
        self.dateEdit_1.setObjectName("dateEdit_1")

        #
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 70, 700, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        #
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(850, 180, 200, 265))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        #
        self.dataLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.dataLayout.setContentsMargins(0, 0, 0, 0)
        self.dataLayout.setObjectName("dataLayout")

        #
        self.lastNameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lastNameLabel.setObjectName("lastNameLabel")

        #
        self.dataLayout.addWidget(self.lastNameLabel)
        self.lastnameEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lastnameEdit.setObjectName("lastnameEdit")
        self.dataLayout.addWidget(self.lastnameEdit)

        #
        self.nameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.dataLayout.addWidget(self.nameLabel)

        #
        self.nameEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nameEdit.setObjectName("nameEdit")
        self.dataLayout.addWidget(self.nameEdit)

        #
        self.midNameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.midNameLabel.setObjectName("midNameLabel")
        self.dataLayout.addWidget(self.midNameLabel)

        #
        self.midNameEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.midNameEdit.setObjectName("midNameEdit")
        self.dataLayout.addWidget(self.midNameEdit)

        #
        self.dateBirthLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dateBirthLabel.setObjectName("dateBirthLabel")
        self.dataLayout.addWidget(self.dateBirthLabel)

        #
        self.dateBirthEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.dateBirthEdit.setObjectName("dateBirthEdit")
        self.dataLayout.addWidget(self.dateBirthEdit)

        #
        self.placeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.placeLabel.setObjectName("placeLabel")
        self.dataLayout.addWidget(self.placeLabel)

        #
        self.placeEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.placeEdit.setObjectName("placeEdit")
        self.dataLayout.addWidget(self.placeEdit)

        #
        self.dateLable_1 = QtWidgets.QLabel(self.centralwidget)
        self.dateLable_1.setGeometry(QtCore.QRect(730, 70, 55, 20))
        self.dateLable_1.setObjectName("dateLable_1")

        #
        self.dateEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(730, 140, 115, 20))
        self.dateEdit_2.setObjectName("dateEdit_2")

        #
        self.codeEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.codeEdit.setGeometry(QtCore.QRect(930, 140, 120, 20))
        self.codeEdit.setObjectName("codeEdit")

        #
        self.dateLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.dateLabel_2.setGeometry(QtCore.QRect(730, 120, 100, 20))
        self.dateLabel_2.setObjectName("dateLabel_2")

        #
        self.codeLabel = QtWidgets.QLabel(self.centralwidget)
        self.codeLabel.setGeometry(QtCore.QRect(930, 120, 120, 20))
        self.codeLabel.setObjectName("codeLabel")

        #
        self.maleLabel = QtWidgets.QLabel(self.centralwidget)
        self.maleLabel.setGeometry(QtCore.QRect(730, 180, 40, 20))
        self.maleLabel.setObjectName("maleLabel")

        #
        self.maleEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.maleEdit.setGeometry(QtCore.QRect(730, 200, 60, 20))
        self.maleEdit.setObjectName("maleEdit")

        #
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 20))
        self.menubar.setObjectName("menubar")

        #
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Passport recognition"))
        self.serLabel.setText(_translate("MainWindow", "Серия"))
        self.ok.setText(_translate("MainWindow", "Все верно"))
        self.exit.setText(_translate("MainWindow", "Закрыть"))
        self.numLabel.setText(_translate("MainWindow", "Номер"))
        self.lastNameLabel.setText(_translate("MainWindow", "Фамилия"))
        self.nameLabel.setText(_translate("MainWindow", "Имя"))
        self.midNameLabel.setText(_translate("MainWindow", "Отчество"))
        self.dateBirthLabel.setText(_translate("MainWindow", "Дата Рождения"))
        self.placeLabel.setText(_translate("MainWindow", "Место Рождения"))
        self.dateLable_1.setText(_translate("MainWindow", "Выдан"))
        self.dateLabel_2.setText(_translate("MainWindow", "Дата выдачи"))
        self.codeLabel.setText(_translate("MainWindow", "Код подразделения"))
        self.maleLabel.setText(_translate("MainWindow", "Пол"))

    def buttonOkClicked(self):
        self.placeBirth = self.placeEdit.text()
        self.male = self.maleEdit.text()

        #name
        self.name = self.nameEdit.text()
        self.midName = self.midNameEdit.text()
        self.lastName = self.lastnameEdit.text()

        self.dateBirth = self.dateBirthEdit.text()
        self.place = self.placeEdit.text()
        self.code = self.codeEdit.text()

        #data
        self.serial = self.serEdit.text()
        self.number = self.numEdit.text()

        #
        self.date_1 = self.dateEdit_1.text()
        self.date_2 = self.dateEdit_2.text()

        self.data = {
            "passport data": {            
                "Имя": self.lastName,
                "Фамилия": self.name,
                "Отчество": self.midName,
                "Пол": self.male,
                "Серия": self.serial,
                "Номер": self.number,  
                "Дата получения": self.date_2,
                "Дата рождения": self.dateBirth,
                "Место получения": self.place,
                "Место рождения": self.placeBirth,
                "Кем выдан": self.date_1,
                "Код подразделения": self.code
            }
        }
        with open("passport_data_file.json", "w", encoding='utf-8') as write_file:
            json.dump(self.data, write_file, sort_keys=False, ensure_ascii=False, separators=(',', ': '))
        print("ok")

        #clear
        self.placeEdit.clear()
        self.maleEdit.clear()
        self.nameEdit.clear()
        self.midNameEdit.clear()
        self.lastnameEdit.clear()
        self.dateBirthEdit.clear()
        self.placeEdit.clear()
        self.codeEdit.clear()
        self.serEdit.clear()
        self.numEdit.clear()
        self.dateEdit_1.clear()
        self.dateEdit_2.clear()

    def setEditData(self, data):

        self.placeEdit.setText(data.placeBirth)
        self.maleEdit.setText(data.male)
        self.nameEdit.setText(data.name)
        self.midNameEdit.setText(data.midName)
        self.lastnameEdit.setText(data.lastName)
        self.dateBirthEdit.setText(data.dateBirth)
        self.placeEdit.setText(data.place)
        self.codeEdit.setText(data.place)
        self.serEdit.setText(data.place)
        self.numEdit.setText(data.number )
        self.dateEdit_1.setText(data.date_1)
        self.dateEdit_2.setText(data.date_2)
    